### ISSUE TITLE
How can you implement ablation without referring to existing tutorials?

### ISSUE THREAD

**Issue by Zmavli** [whitebox-research/excursions#13]
# Todos
- [x] Ablate a neuron and verify with `circuitsvis`
- [ ] Generate text with the ablated activations
- [ ] Learn how to use hooks with `run_with_hooks`
